In [19]:
import numpy as np

Powerful way to process multidimensional data

In [2]:
import pandas

Pandas = PANel DAta

Pandas enhances Numpy even further - it allows us to organize data in a tabular format and to attach descriptive labels to the rows and the columns of the table, not just numbers as it is with Numpy. Furthermore, Pands is endowelled with a broad gama of tools facilitating our work with various data formats and missing data - used in time series and huge databases

In [5]:
import matplotlib

When your calculations are ready, we should be able to visualize the data. Matplotlib is a 2 dimensional plotting library specially designed to work with pandas - it contains a large set of tools to adjust graphs to your liking.

Numpy, Pandas and Matplotlib are part of a larger ecosystem of tools called SciPy, which include specializes tools for working in the field of mathematics, machine learning, artificial intelligence, and engineering.

In [15]:
import math

Mathematical functions

In [17]:
import random

Random is for generating random numbers

In [18]:
import statsmodels

Statsmodels - descriptive statistics, plotting functions and regressions

In [13]:
import pandas_datareader

In [27]:
a = np.array([[0,1,2,3], [4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

N-dimensional array = ndarray. A ndarray is always homogeneous.

In [28]:
a.shape

(2, 4)

In [32]:
a[1,0] or a[1][0]

4

In [33]:
a[1,0] = 8

In [34]:
a

array([[0, 1, 2, 3],
       [8, 5, 6, 7]])

In [38]:
prob = random.random()
prob

0.7921124395874395

In [40]:
prob = random.randint(1,6)
prob

2

In [41]:
import numpy as np

In [42]:
np.random.randint(1,6,(4,6))

array([[5, 5, 5, 1, 4, 2],
       [1, 1, 4, 1, 1, 4],
       [2, 2, 1, 4, 4, 5],
       [4, 5, 5, 4, 5, 1]])

This generates a random 4x6 matrix with random numbers from 1 to 6 - this will be useful later when we work with Monte Carlo simulations